Support SM4
stefanberger/libtpms pull request #272
Opened 2021-10-11 14:22 UTC by JerryDevis

Support SM4 algorithm

2021-10-11 16:21 UTC, stefanberger commented
I wonder whether the TPM 2 code is in general prepared for the type of expansion of plaintext versus ciphertext. In the example 32 bytes input with SM4 become 48 bytes output. My concern would be that this could lead to buffer overruns or failure mode if large input data are given.

2021-10-12 02:34 UTC, JerryDevis commented
> This fixes the test issue it seems:
> 
> ```
> diff --git a/src/tpm2/SymmetricTest.h b/src/tpm2/SymmetricTest.h
> index 058f50a..8083191 100644
> --- a/src/tpm2/SymmetricTest.h
> +++ b/src/tpm2/SymmetricTest.h
> @@ -96,7 +96,7 @@ const SYMMETRIC_TEST_VECTOR   c_symTestValues[NUM_SYMS + 1] = {
>  #if ALG_SM4 && SM4_128 // libtpms activated
>      {TPM_ALG_SM4, 128, key_SM4128, 16, sizeof(dataIn_SM4128), dataIn_SM4128,
>       {dataOut_SM4128_CTR, dataOut_SM4128_OFB, dataOut_SM4128_CBC,
> -      dataOut_SM4128_CFB, dataOut_AES128_ECB}},
> +      dataOut_SM4128_CFB, dataOut_SM4128_ECB}},
>  #endif
>  // libtpms added begin
>  #if ALG_TDES && TDES_128
> ```
Ok，I have fixed it.

2021-10-12 10:46 UTC, stefanberger requested changes
It's mostly about adding these comments to the code now and removing white spaces. I have the comments in many other places and they help me skip over this stuff when synchronizing with the reference code. Ideally they would all disappear at some point when the reference code has the SM 4 support as well...

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/Marshal_fp.h
> +#if ALG_SM4 			// libtpms begin
libtpms added begin

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/CryptSym.h
> +#define FINAL(keySchedule) final((void *)(keySchedule))
libtpms added

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/CryptSym.h
> +    final = (TpmCryptSymFinal_t)TpmCryptFinal##ALG;          \
libtpms added

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/CryptSym.h
> +    final = (TpmCryptSymFinal_t)TpmCryptFinal##ALG;          \
libtpms added

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/openssl/CryptCmac.c
> +    TpmCryptSetSymKeyCall_t  encrypt;
it looks like you added a whitespace to the end of this line...

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/openssl/CryptCmac.c
> +    TpmCryptSymFinal_t       final;
comment: /* libtpms added */

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/openssl/CryptCmac.c
> +    if (final)
comment: /* libtpms added begin */   and then /* lbtpms added end */

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/openssl/CryptCmac.c
> +    TpmCryptSymFinal_t       final;
/* libtpms added */

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/openssl/CryptCmac.c
> +    if (final)
comment: /* libtpms added begin / and then / lbtpms added end */

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/openssl/CryptSym.c
> +    TpmCryptSymFinal_t       final;
comment: /* libtpms added */

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/openssl/CryptSym.c
> +	  	if (final)
comment ...

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/openssl/CryptSym.c
> +	TpmCryptSymFinal_t       final;
comment ...

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/openssl/CryptSym.c
> +	    if (final)
comment ...

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/openssl/TpmToOsslSym.h
> +#define TpmCryptFinalAES            NULL
comment ...

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/openssl/TpmToOsslSym.h
> +    SM4_set_encrypt_key((key), (tpmKeyScheduleSM4 *)(schedule))
/* libtpms changed */

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/openssl/TpmToOsslSym.h
> +    SM4_set_decrypt_key((key), (tpmKeyScheduleSM4 *)(schedule))
/* libtpms changed */

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/openssl/TpmToOsslSym.h
> +#define TpmCryptFinalTDES           NULL
comment ...

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/openssl/TpmToOsslSym.h
> +#define TpmCryptFinalSM4            SM4_final
comment ...

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/crypto/openssl/TpmToOsslSym.h
> +#define TpmCryptFinalCAMELLIA            NULL
comment ...

2021-10-12 10:46 UTC, stefanberger commented on src/tpm2/AlgorithmTests.c
> +		  case TPM_ALG_SM4:
comment: /* libtpms changed */

2021-10-12 14:57 UTC, merged

2021-10-12 15:54 UTC, JerryDevis commented
There are also some problems with implementing these algorithms ourselves.
Firstly, these algorithms, which we implemented ourselves, lack the certification of some security organizations.
Secondly, OpenSSL or other cryptographic library suites use some assembly language to accelerate the algorithms, If we do not consider these, then the performance of our implemented algorithm will be poor.
For the future, this is indeed a very troublesome problem.

2025-09-02 15:53 UTC, stefanberger commented
@JerryDevis Hello. Are you still around? I need to talk to you about the SM4 support due to a rebasing effort on a new (TCG) upstream with a different license (BSD-2 clause). Since I am not currently enabling the SM4 support I would remove it before the re-base so that you could re-added it later on again under the new license.

2025-09-02 16:15 UTC, fly2x commented
JerryDevis is on leave. We're from the same team. Once you finish the re-base, we'll resubmit.