RSA encrypt fix set label for OpenSSL 3.0
stefanberger/libtpms pull request #294
Opened 2022-02-19 12:24 UTC by JuergenReppSIT

Openssl 3.0 did return an error if EVP_PKEY_CTX_set0_rsa_oaep_label was called
with label size 0. The function should only be called if the size of the label
is greater 0.
With this fix TPM2_RSA_Encrypt/Decrypt did work with OpenSSL 1.1 and 3.0
for encryption without label.

Signed-off-by: Juergen Repp <juergen.repp@sit.fraunhofer.de>

2022-03-01 19:09 UTC, stefanberger requested changes

2022-03-01 19:09 UTC, stefanberger commented on src/tpm2/crypto/openssl/CryptRsa.c
> -                if (EVP_PKEY_CTX_set0_rsa_oaep_label(ctx, tmp, label->size) <= 0)
I don't think in this case it is necessary to again check label->size > 0. The whole block is already protected with this check.

2022-03-01 19:09 UTC, stefanberger commented on src/tpm2/crypto/openssl/CryptRsa.c
> +            if (label->size > 0 && EVP_PKEY_CTX_set0_rsa_oaep_label(ctx, tmp, label->size) <= 0)
Can you move the EVP_PKEY_CTX_set0_rsa_oaep_label() into the block above it that already checks for label->size > 0.

2022-03-01 19:29 UTC, stefanberger commented
FYI: This here is the OpenSSL 1.1.1 that still allowed label to be NULL: https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/crypto/rsa/rsa_pmeth.c#L545-L550

2022-03-01 19:36 UTC, stefanberger commented
Can you also please adjust the title of the patch to something like `tpm2: Do not call EVP_PKEY_CTX_set0_rsa_oaep_label() for label of size 0 (OSSL 3)`

2022-03-01 20:55 UTC, stefanberger commented on src/tpm2/crypto/openssl/CryptRsa.c
> +                if (label->size > 0 && EVP_PKEY_CTX_set0_rsa_oaep_label(ctx, tmp, label->size) <= 0)
I don't think in this case it is necessary to again check label->size > 0. The whole block is already protected with this check.

2022-03-02 08:46 UTC, JuergenReppSIT commented
> FYI: This here is the OpenSSL 1.1.1 that still allowed label to be NULL: https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/crypto/rsa/rsa_pmeth.c#L545-L550
@stefanberger Thank you for the info. Yes in our CI for tss we have three test cases with label size 0 which did always work. During the first tests with Ubuntu 22.04 using libtpms installed via apt the errors did occur.

2022-03-02 12:24 UTC, merged

2022-03-02 12:24 UTC, stefanberger commented
Thanks!

2026-01-20 22:53 UTC, stefanberger commented
@JuergenReppSIT More recent TPM 2 code is under the BSD-2-Clause license. Do you mind this contribution to move under this 'new' license once the file that you applied the patch to moves under that license? If not I would have to revert the patch...

2026-01-21 07:15 UTC, JuergenReppSIT commented
> @JuergenReppSIT More recent TPM 2 code is under the BSD-2-Clause license. Do you mind this contribution to move under this 'new' license once the file that you applied the patch to moves under that license? If not I would have to revert the patch...

@stefanberger Yes, I would agree to that.

2026-01-21 14:14 UTC, stefanberger commented
> > @JuergenReppSIT More recent TPM 2 code is under the BSD-2-Clause license. Do you mind this contribution to move under this 'new' license once the file that you applied the patch to moves under that license? If not I would have to revert the patch...
> 
> @stefanberger Yes, I would agree to that.

@JuergenReppSIT Thanks.